blank_issues_enabled: true
contact_links:
  - name: pixel.horse Discord server
    url: https://chat.pixel.horse/
    about: "Ask questions regarding setup and configuration in the #custom-server-support channel here."
